In [64]:
import time
import requests
import json
import re
import pandas as pd

headers = {'User-Agent':
               'Mozilla/5.0 (Windows NT 10.0; WOW64)\
               AppleWebKit/537.36(KHTML, like Gecko)\
               Chrome/55.0.2883.87 Safari/537.36'}

namelist = []


for i in range(1,1000):
    print(i)
    url = 'https://www.javbus.com/genre/3k/'+ str(i)

    web = requests.get(url, headers=headers)
    web.encoding = 'utl-8'

    Page = web.text

    #Js = json.loads(str(Page))
    FFF = re.findall(r'class="movie-box" href=".*?">', Page)
    #print(Page)

    #print(FFF)
    if len(FFF)<5 : 
        break
    for item in FFF:
        end = item.rindex('"')
        #print (item[47:end])
        namelist.append(item[47:end])
        

df1 = pd.DataFrame(namelist)
df1.columns=['Name']
df1['small']=True

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21

In [65]:
import time
import requests
import json
import re
import pandas as pd

headers = {'User-Agent':
               'Mozilla/5.0 (Windows NT 10.0; WOW64)\
               AppleWebKit/537.36(KHTML, like Gecko)\
               Chrome/55.0.2883.87 Safari/537.36'}

namelist = []


for i in range(1,1000):
    print(i)
    url = 'https://www.javbus.com/genre/w/'+ str(i)

    web = requests.get(url, headers=headers)
    web.encoding = 'utl-8'

    Page = web.text

    #Js = json.loads(str(Page))
    FFF = re.findall(r'class="movie-box" href=".*?">', Page)
    #print(Page)

    #print(FFF)
    if len(FFF)<5 : 
        break
    for item in FFF:
        end = item.rindex('"')
        #print (item[47:end])
        namelist.append(item[47:end])
        

df2 = pd.DataFrame(namelist)
df2.columns=['Name']
df2['lolita']=True

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124

NameError: name 'df' is not defined

In [68]:
df_merge = pd.merge(df1,df2,how='left')
df_merge.to_csv('out.csv', index=False, header=True)

In [70]:
df2

            Name  lolita
0       ID-035-6    True
1       SDMU-844    True
2       REAL-676    True
3       NKKD-090    True
4       SDMU-826    True
5       WANZ-773    True
6      ID-021-11    True
7       ID-024-9    True
8       DOCP-047    True
9        DDK-174    True
10      MIDE-558    True
11      SDMU-813    True
12      FP-007-2    True
13      ID-020-7    True
14      KMHR-036    True
15      DOCP-041    True
16      KDKJ-065    True
17      EYAN-117    True
18      SDMU-800    True
19      FSTA-016    True
20      SDAB-057    True
21      FSRE-001    True
22      FSRE-002    True
23      SQTE-207    True
24      INCT-022    True
25      AMBI-090    True
26      EKDV-526    True
27      AMBS-042    True
28      IBW-667Z    True
29      IBW-665Z    True
...          ...     ...
3645     GOD-007    True
3646   DCM-011-2    True
3647    SFLB-024    True
3648    GS-012-1    True
3649    AV-104-1    True
3650    SFLB-073    True
3651    GS-089-1    True
3652     RAP-002    True
3653       S-062    True
3654    UPGD-002    True
3655     SPZ-095    True
3656    AA-011-2    True
3657   PRE-001-2    True
3658  LINE-001-1    True
3659   DRD-001-2    True
3660   MBD-141-2    True
3661    MIDE-466    True
3662   SHI-009-1    True
3663     HND-434    True
3664    MG-001-1    True
3665   CLB-001-1    True
3666    LINE-012    True
3667    GS-109-1    True
3668  ONED-924-1    True
3669    ID-006-5    True
3670   CRZ-001-1    True
3671   MOM-032-1    True
3672    CJOD-100    True
3673      SM-101    True
3674   MAD-091-2    True

[3675 rows x 2 columns]

In [66]:
df2['lolita']=True

In [20]:
import urllib.request
import urllib.error
try:
    headers = {'User_Agent': 'Mozilla/5.0 (X11; Ubuntu;Linux x86_64; rv:57.0) Gecko/20100101  Firefox/57.0'}
    response = urllib.request.Request('https://www.baidu.com', headers=headers)
    html = urllib.request.urlopen(response)
    result = html.read().decode('utf-8')
except urllib.error.URLError as e:
    if hasattr(e, 'reason'):
        print('错误原因是' + str(e.reason))
except urllib.error.HTTPError as e:
    if hasattr(e, 'code'):
        print('错误状态码是' + str(e.code))
else:
    print('请求成功通过。')

请求成功通过。